### ISSUE TITLE
打开是这个怎么解决

### ISSUE THREAD

**Issue by LUEDD** [vfaner/mobile_mall#1]
<img width="952" alt="屏幕截图 2022-03-11 115140" src="https://user-images.githubusercontent.com/101379319/157799666-655e7fdd-fb1f-4bcb-83b1-edeed344dddf.png">

**Comment by vfaner** [comment]
The front end needs to obtain data from the back end. Obviously, this is caused by the failure to obtain data. The back end may not be running or cross domain problems may not be handled properly
